"""What the actions need from GitHub; implemented by RunControl and ContentsClient."""

from datetime import datetime
from typing import Protocol

from flakipype.github.runs import JobState, RunState


class RunApi(Protocol):
    def rerun_failed_jobs(self, repository: str, run_id: int) -> None: ...

    def rerun(self, repository: str, run_id: int) -> None: ...

    def cancel(self, repository: str, run_id: int) -> None: ...

    def dispatch(self, repository: str, workflow_path: str, ref: str) -> int | None: ...

    def dispatched_runs(
        self, repository: str, workflow_path: str, *, ref: str, since: datetime
    ) -> list[int]: ...

    def run_state(self, repository: str, run_id: int) -> RunState: ...

    def job_states(self, repository: str, run_id: int, attempt: int) -> list[JobState]: ...

    def default_branch(self, repository: str) -> str: ...

    def ref_commit(self, repository: str, ref: str) -> str | None: ...


class WorkflowFiles(Protocol):
    def file_content(self, repository: str, path: str, ref: str) -> str | None: ...
